### ISSUE TITLE
'make stop' not stopping containers

### ISSUE THREAD

**Issue by blourdel** [Juniper/open-nti#108]
From the documentation :https://github.com/Juniper/open-nti/blob/master/docs/troubleshoot.rst
containers can be stopped with 'make stop'

Here is the output of it on my system:

root@xxxx:/root/open-nti# make stop
echo "Use docker compose file : docker-compose.yml"
Use docker compose file : docker-compose.yml
docker-compose -f docker-compose.yml down
No such command: down

Commands:
  build              Build or rebuild services
  help               Get help on a command
  kill               Kill containers
  logs               View output from containers
  pause              Pause services
  port               Print the public port for a port binding
  ps                 List containers
  pull               Pulls service images
  restart            Restart services
  rm                 Remove stopped containers
  run                Run a one-off command
  scale              Set number of containers for a service
  start              Start services
  stop               Stop services
  unpause            Unpause services
  up                 Create and start containers
  migrate-to-labels  Recreate containers to add labels
  version            Show the Docker-Compose version information
Makefile:35: recipe for target 'stop' failed
make: *** [stop] Error 1

**Comment by dgarros** [comment]
Hi @blourdel 

Something must be different on your system, `make stop` is working for me.  
Please could you collect the output of :
```
docker-compose -v
docker -v
```
Also please can you indicate with OS/ver you are using ?
  
I'm using  
```
docker-compose version 1.8.0-rc1, build 9bf6bc6
Docker version 1.12.0-rc2, build 906eacd, experimental
```
thanks

**Comment by blourdel** [comment]
Hello,

I had   docker-compose version 1.5.2, build unknown installed.

I upgraded. It works now. 

thanks

Benoit

**Comment by dgarros** [comment]
perfect
