### ISSUE TITLE
MPLS LSP stats @ grafana

### ISSUE THREAD

**Issue by hz2102** [Juniper/open-nti#115]
Hi

Is MPLS LSP stats can be plotted by grafana?
I have a vMX with 16.1R3 and appropriate sensor is already configured.
I can also netcat packets sent by vMX and decode successfully.

The problem I am facing is, Grafana with its predefined "Data Streaming Collector Dashboard" shows nothing.
 Row: MPLS LSP
 Graph: LSP Traffic Rate (PPS)
 Metrics: SELECT "value" FROM "jnpr.jvision" WHERE "type" = 'lspstata.packet_rate' AND "device" =~ /$host_regex$/ AND $timeFilter GROUP BY "device", "lspname"

By the way, LSP traffic Rate BPS also shows nothing.

Regards

**Comment by hz2102** [comment]
I think i found the answer.
Issue #106 @dgarros  wrote "LSP should work but I have done little testing on it"

@dgarros Let me know if you have any results on this :)

**Comment by 3fr61n** [comment]
Hi @hz2102 

Are you still seen the issue?

Regards
Efrain

**Comment by hz2102** [comment]
Hi Efrain,

Yes, I have just checked now again with lsp ping, routing-instance ping.
On both cases interface counter and grafana counts up.
But no change in LSP graph of grafana.
By the way, show "mpls lsp statistics" also counts up @ vMX

Regards

**Comment by 3fr61n** [comment]
Could you please check through influxdb web ui and check if there is any value in this measurement?

(Something like 'SELECT "*" FROM "jnpr.jvision" WHERE "type" = 'lspstata.packet_rate' , if this fails, try to check single/double quotes (this is a tricky thing in influxdb))

Regards

**Comment by hz2102** [comment]
Thanks.

[SELECT "*" FROM "jnpr.jvision" WHERE "type" = 'lspstata.packet_rate'] works well,
But influxdb replies "Success! (no results to display)".
So fluentd may be doing something wrong here?

**Comment by 3fr61n** [comment]
If you tried with others queries changing the "type" and it returns values  (so the single/double quotes and query string is valid), then we can confirm that the issue is in fluentd

**Comment by hz2102** [comment]
I have tried [SELECT "*" FROM "jnpr.jvision" WHERE "type" = 'egress_stats.if_octets'] but the output was same "Success! (no results to display)".
Can you please provide me, what output influxdb should show?

**Comment by 3fr61n** [comment]
For instance in my setup I executed 
`select * from "jnpr.jvision" where "type"= 'egress_stats.if_pkts' limit 10` and got the following result  (remember to pay attention to single/double quotes are kind of tricky)

<img width="1004" alt="screen shot 2017-01-26 at 13 05 10" src="https://cloud.githubusercontent.com/assets/6707509/22330766/24359842-e3c8-11e6-9022-21ba03464c23.png">

If you want to check which 'types' do you have in your db, you can execute
`SHOW TAG VALUES FROM "jnpr.jvision" WITH KEY = "type"` 

Please check if any of mpls lsp stats are on that result.

**Comment by hz2102** [comment]
Thanks again.

I have got some the following results.
=========================================
SHOW TAG VALUES FROM "jnpr.jvision" WITH KEY = "type"
===>
key	value
type	"egress_stats.if_octets"
type	"egress_stats.if_packets"
type	"ingress_stats.if_mcast_packets"
type	"ingress_stats.if_octets"
type	"ingress_stats.if_packets"
type	"ingress_stats.if_ucast_packets"
type	"lsp_stats.byte_rate"
type	"lsp_stats.bytes"
type	"lsp_stats.packet_rate"
type	"lsp_stats.packets"
=========================================

=========================================
select * from "jnpr.jvision" where "type"= 'egress_stats.if_packets' limit 10
and
select * from "jnpr.jvision" where "type"= 'lsp_stats.byte_rate' limit 10
shows counters
=========================================

So the problem was in Grafana's defination
Before->
 SELECT "value"*8 FROM "jnpr.jvision" WHERE "type" = 'lsp_stata.byte_rate' AND "device" =~ /$host_regex$/ AND $timeFilter GROUP BY "device", "lspname", "type"

after I change this to ->
 SELECT "value"*8 FROM "jnpr.jvision" WHERE "type" = 'lsp_stats.byte_rate' AND "device" =~ /$host_regex$/ AND $timeFilter GROUP BY "device", "lspname", "type"
Graph are shown now :)

Thank you so much for your time troubleshooting this.
I will read carefully next time :)
