### ISSUE TITLE
Getting error when running 'docker.start.sh' 

### ISSUE THREAD

**Issue by skm007** [Juniper/open-nti#116]
Not able to start open-nti containers using 'docker.start.sh'

root@ubuntu:~/open-nti# ./docker.start.sh 
Use docker compose file : docker-compose.yml
**WARNING: The IMAGE_TAG variable is not set. Defaulting to a blank string.**
Pulling opennti (juniper/open-nti:latest)...
latest: Pulling from juniper/open-nti
Digest: sha256:1bc00e223477fce1bdb47c4206ea6bf8c5ea01ee4adca2191043ca5b8891acfb
Status: Image is up to date for juniper/open-nti:latest
Pulling input-syslog (juniper/open-nti-input-syslog:latest)...
latest: Pulling from juniper/open-nti-input-syslog
Digest: sha256:69603d75bf645267dbe48e6f17fe6c5010cf5ae53c5ad9ada0d3b0a4c1c15519
Status: Image is up to date for juniper/open-nti-input-syslog:latest
Pulling input-jti (juniper/open-nti-input-jti:latest)...
latest: Pulling from juniper/open-nti-input-jti
Digest: sha256:9eb80f329e25a6cdc3767c50329e0df05edcabc3c3eae8288a11fb3b518eb3c4
Status: Image is up to date for juniper/open-nti-input-jti:latest
Pulling opennti (juniper/open-nti:latest)...
latest: Pulling from juniper/open-nti
Digest: sha256:1bc00e223477fce1bdb47c4206ea6bf8c5ea01ee4adca2191043ca5b8891acfb
Status: Image is up to date for juniper/open-nti:latest

**ERROR: for opennti  Image 'juniper/open-nti:' not found**
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 61, in main
  File "compose/cli/main.py", line 113, in perform_command
  File "compose/cli/main.py", line 835, in up
  File "compose/project.py", line 400, in up
  File "compose/parallel.py", line 64, in parallel_execute
compose.service.NoSuchImageError: Image 'juniper/open-nti:' not found

**Comment by dgarros** [comment]
Got it
 
All the docker.*.sh scripts are deprecated, moving forward it’s recommended to use “make”
 
You can use
```
make start
make stop
make update
etc …
``` 
I’ll try to see if I can fix docker.start.sh but we’ll remove it soon
