### ISSUE TITLE
Easiest way to create get graphs for all interfaces 

### ISSUE THREAD

**Issue by 3fr61n** [Juniper/open-nti#135]
This is a spin off for #89 

@rpetracic   

There are a few options.

1.- Single chart + templating:  This approach is the one we mostly use in actual dashboards, you need to create a new chart with a query like /$host_regex.interface..*.input-bps/ so in this chart it will draw ALL interfaces belonging to the hostname you have selected in the template.

2.- Dashboard generator tool:  Our colleague @dgarros build a script that parse a yaml file with a list of queries, and it will create the whole dashboard in json format.  If you often modify the dashboards this option is the best approach.

The tool is https://github.com/Juniper/open-nti/blob/master/dashboards/gendashboard.py, and you'll find some examples because jti dashboard is generated with this.

3.- One dashboard per device with multiple charts (one per interface):   Scripted dashboards is the option here (http://docs.grafana.org/reference/scripting/)  basically you have an 'url' for each device, that url is a javascript (that you develop as you like) and it receives some arguments (for instance hostname) then it can perform queries to the database and generate dynamically all required charts.

Regards
Efrain

**Comment by nembery** [comment]
Just wanted to leave a comment that this query worked for me for a single interface:
select mean(value) from /($host_regex).interface.ge-0\/0\/0.*/ where $timeFilter group by time($interval)
I also had to set the datasource as influxdb and the groupby time interval to 60s.

**Comment by 3fr61n** [comment]
Thanks @nembery 

group by time interval is usually tricky :) ,  A general rule is to set it greater or equal to you polling interval if you want to graph anything,  in some special cases you need also to add the 'fill()' statement for those periods of time no samples are found
