### ISSUE TITLE
Grafana query issue for CPU Idle graph

### ISSUE THREAD

**Issue by mziegler8888** [Juniper/open-nti#138]
Hi All,

we are using the latest Grafana version 4.2.* and i just moved some graphs from the open-nti grafana. Unfortunately it looks like the templating no longer works properly with 4.*.
For example the "RE - CPU Idle" graph. Graphing a single device works. When selecting "All" devices it looks like Grafana is selecting all metrics for all devices. Please see attached screenshots.

Any ideas? Or do I have to submit an issue to the Grafana project?

Thanks, Martin

![screen-shot-2017-02-24-at-10 35 20](https://cloud.githubusercontent.com/assets/22808391/23298515/40103f82-fa7e-11e6-8363-af49fe95789f.jpg)
![screen-shot-2017-02-24-at-10 34 54](https://cloud.githubusercontent.com/assets/22808391/23298516/40124822-fa7e-11e6-914f-968593fb3e18.jpg)

**Comment by 3fr61n** [comment]
Hi Martin

I reproduced on my setup, it seems a problem with grafana and processing templating, let's do some research on grafana if there is some issue related

Thanks for comment it

**Comment by 3fr61n** [comment]
Hi

I noticed that by "default" in this grafana version somehow when you check 'All' or 'multiple options' it translate  $host_regex into "host1|host2|host3"  and not in  ".*" (in case of ALL) or "(host1|host2|host3)" in case of multiple hosts.

With this behaviour the query looks like

select mean(value) from /host1|host2|host3.chassis.routing-engine.*.cpu-idle/ where time > now() - 1h group by time(15s)&epoch=ms

This means  the regex will match ALL variables that begins with host1 and host2, but only a few variables for host3.

Quick workaround.

1.- Edit $host_regex variable and set a default value for All option to .*  (see diagram below)

![screen shot 2017-02-24 at 15 34 52](https://cloud.githubusercontent.com/assets/6707509/23307692/bec46bb2-faa8-11e6-909c-909d2b8e743c.png)

2.- Edit all dashboards queries and replace $host_regex by ($host_regex)

Solution 1, only fix ALL option but multiple option will be still broken
Solution 2, will fix both scenarios but require rewrite all dashboards.

Regards
Efrain

**Comment by mziegler8888** [comment]
Very nice...thank you!

**Comment by 3fr61n** [comment]
Could you please check this commit and test it 

https://github.com/Juniper/open-nti/tree/fix-grafana-template-variable

Thanks in advance

**Comment by mziegler8888** [comment]
Works fine. Thank you.
