### ISSUE TITLE
How to graph LAG interfaces (ae0 etc)

### ISSUE THREAD

**Issue by nzjc** [Juniper/open-nti#140]
Hi 

Is it possible to graph AE interfaces? When I run this I see lots of xe/et/ge interfaces show up, but none of the ae interfaces.

Thanks

**Comment by 3fr61n** [comment]
Hi @nzjc 

What kind of method are you using for data collection?  jti/data streaming  or netconf/data collection agent?

Regards

**Comment by nzjc** [comment]
hi @3fr61n - I am trying to use both - but in this case I am using jti/data streaming. It picks up the interfaces that make up my lags, but not the lag themselves. Obviously I would want the errors from the physical interfaces, but aggregate traffic for the lag is what I'd need to see before I can replace Cacti :)

**Comment by 3fr61n** [comment]
If you're using jti, is pretty straight forward.. as you can see in the screenshot below, if you perform a database query, there is a tag called 'interface_parent' that links the physical stats with the related aeX.

![screen shot 2017-02-27 at 18 39 55](https://cloud.githubusercontent.com/assets/6707509/23372515/3a42f680-fd1c-11e6-93c1-b7de44a28027.png)

So you just need to group all physical interfaces by interface_parent then sum the related value. (in the example I did not sum just to show the deagregated query result

![screen shot 2017-02-27 at 18 47 50](https://cloud.githubusercontent.com/assets/6707509/23372750/3af6a116-fd1d-11e6-8dff-e82b258146a6.png)

In case you're using the netconf data collection, doing the proper parsing for 'show interfaces' or 'show interface media' should be enough to gather aeX statistics.

Regards
Efrain

**Comment by 3fr61n** [comment]
Solved
