### ISSUE TITLE
Issue wit make start

### ISSUE THREAD

**Issue by gavmckee80** [Juniper/open-nti#141]
Hi,

I'm getting the following error when running make start

gmckee@ubuntu:~/projects/open-nti$ make start
Use docker compose file: docker-compose.yml
IMAGE_TAG=latest docker-compose -f docker-compose.yml up -d
opennti_con is up-to-date
opennti_input_syslog is up-to-date
Building input-internal
Step 1 : FROM juniper/pyez:2.0.1
 ---> e61c159ee89f
Step 2 : WORKDIR /source
 ---> Using cache
 ---> 94061a89bacb
Step 3 : USER root
 ---> Using cache
 ---> 1da07373c6a4
Step 4 : RUN apk add --no-cache ca-certificates &&     update-ca-certificates
 ---> Using cache
 ---> f12db98cc32b
Step 5 : RUN apk add --no-cache wget git
 ---> Running in 01dbf26efaad
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
  git (missing):
    required by: world[git]
  wget (missing):
    required by: world[wget]
ERROR: Service 'input-internal' failed to build: The command '/bin/sh -c apk add --no-cache wget git' returned a non-zero code: 2
Makefile:69: recipe for target 'start' failed
make: *** [start] Error 1

**Comment by 3fr61n** [comment]
Not sure why but sometimes it happens with docker daemon it lost connectivity (dns), can you restart your docker daemon and retry?

Thanks

**Comment by gavmckee80** [comment]
It seems to be a DNS issue within docker

gmckee@ubuntu:~/projects/open-nti$ sudo systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; disabled; vendor preset: enabled)
   Active: active (running) since Thu 2017-03-09 11:54:15 PST; 20s ago
     Docs: https://docs.docker.com
 Main PID: 2701 (dockerd)
   CGroup: /system.slice/docker.service
           ├─2701 /usr/bin/dockerd -H fd://
           ├─2728 containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --shim containerd-shim --metrics-interval=0 --start-timeout 2m 
           ├─3043 /usr/bin/docker-proxy -proto udp -host-ip 0.0.0.0 -host-port 8125 -container-ip 172.17.0.2 -container-port 8125
           ├─3054 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8086 -container-ip 172.17.0.2 -container-port 8086
           ├─3062 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8083 -container-ip 172.17.0.2 -container-port 8083
           ├─3070 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 3000 -container-ip 172.17.0.2 -container-port 3000
           ├─3078 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 80 -container-ip 172.17.0.2 -container-port 80
           ├─3083 containerd-shim 872c5a68ec587e6ce9740122a5685c1a6e12670ecc6e822a66434f48eaa81c0e /var/run/docker/libcontainerd/872c5a68ec587e6ce9740122a5
           ├─3174 /usr/bin/docker-proxy -proto udp -host-ip 0.0.0.0 -host-port 6000 -container-ip 172.17.0.3 -container-port 6000
           └─3188 containerd-shim 4ce13b1a5ce05d4046da01cb650b61475c0407188c66f85e8829c0066e180516 /var/run/docker/libcontainerd/4ce13b1a5ce05d4046da01cb65

Mar 09 11:54:15 ubuntu dockerd[2701]: time="2017-03-09T11:54:15.678769624-08:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. 
Mar 09 11:54:15 ubuntu dockerd[2701]: time="2017-03-09T11:54:15.681450947-08:00" level=info msg="IPv6 enabled; Adding default IPv6 external servers : [name
Mar 09 11:54:16 ubuntu dockerd[2701]: time="2017-03-09T11:54:16.207616067-08:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. 
Mar 09 11:54:16 ubuntu dockerd[2701]: time="2017-03-09T11:54:16.212003667-08:00" level=info msg="IPv6 enabled; Adding default IPv6 external servers : [name
Mar 09 11:54:16 ubuntu dockerd[2701]: time="2017-03-09T11:54:16.675636825-08:00" level=error msg="Handler for GET /v1.19/images/opennti_input-internal/json

**Comment by gavmckee80** [comment]
i'm not sure how to fix this, any ideas?

**Comment by 3fr61n** [comment]
Service docker restart :)

**Comment by gavmckee80** [comment]
Work around:

Create a file like so
/etc/docker/daemon.json:
Add DNS servers

{
    "dns": ["X.X.X.X", "Y.Y.Y.Y"]
}

sudo service docker restart

:)

**Comment by 3fr61n** [comment]
Thanks for the tip  @gavmckee80
