### ISSUE TITLE
How to clean host_regex dropdown menu

### ISSUE THREAD

**Issue by cduranm** [Juniper/open-nti#152]
Hi, 

I have open-nti installed as per procedure http://open-nti.readthedocs.io/en/latest/install.html 
I'm trying to delete hostnames/devices from the host_regex dropdown menu in Grafana:

~/open-nti/data/hosts.yaml file is now empty.

I deleted the influx DB via CLI...
> :~/open-nti$ sudo make cli
> docker exec -i -t opennti_con /bin/bash
> root@a7bd80d8e60b:/# for i in $(influx -database=juniper -execute="SHOW MEASUREMENTS" | grep ptx)
> root@a7bd80d8e60b:/# do
 > root@a7bd80d8e60b:/# noterminal=$(influx -database=influxdb -execute="drop measurement \"$i\"")
> root@a7bd80d8e60b:/# echo "$i = $?"
> root@a7bd80d8e60b:/# done

... also tried to delete from InfluxDB , port 8083 using the DROP MEASUREMENT procedure (https://docs.influxdata.com/influxdb/v0.13/query_language/database_management/#delete-measurements-with-drop-measurement), and reboot the entire VM. 
The hostnames I initially had into the ~/open-nti/data/hosts.yaml file won't disappear from the host_regex dropdown menu. 

Please advice on how to clean this up.

Thanks,
Carlos

**Comment by 3fr61n** [comment]
Hi Carlos, 

The hosts dropdown takes the information from influxdb, and **depending of how is your dashboard configured**, that list is updated each time the dashboard is reloaded, or it could even never being refreshed.

If you already delete all measurements from influxdb, and the dropdown lists is still there, please try to go through the grafana dashboard settings -> templating -> edit the host_regex variable -> select update.

Let me know if this works for you

Regards
Efrain

**Comment by 3fr61n** [comment]
Checking your database the query for **SHOW TAG VALUES WITH KEY = "device"** returns some values coming from "open-nti-stats" measurement, so after removing that measurement from your database with  **DROP MEASUREMENT "open-nti-stats"**, the host_regex dropdown is empty.
