### ISSUE TITLE
Make start-persistent doesn't keep data

### ISSUE THREAD

**Issue by zhanghaofeng** [Juniper/open-nti#154]
I am using make start-persistent mode according to docs:
By default it will start 3 containers and it's working in non-persistent mode, once you stop it all data are gone. It's possible to start the main container in persistent mode to save the database outside the container, b y using the startup script make start-persistent. Persistent mode on Mac OS requires at least v1.12

But even this, after I "make stop-persistent", "make-start-persisent" again, all the data in inFluxdb is gone. 
How can I keep my data?

**Comment by zhanghaofeng** [comment]
need to docker commit before stop the containers.
After that, data stats are kept.

**Comment by 3fr61n** [comment]
Hi

One question, with data do you mean influxdb data or grafana data?

Because, so far, the persistent mode consist of include a volume to map only influxdb database directory to a host directory outside of container.

If you need persistency on grafana I suggest to save you dashboard in json format in the /dashboard directory outside the container

Let me know if this works for you

Regards

**Comment by zhanghaofeng** [comment]
I mean influxdb data.
The problem is, if I only use “make start-persistent”, database data will be still lost after I restart dockers.
The workaround is to run “docker commit” before restarting dockers. Thus I can keep the data.

Is it expected behavior?

**Comment by 3fr61n** [comment]
Let me do some testing

**Comment by zhanghaofeng** [comment]
Thanks for looking into this.
Just FYI, the first run of “make start-persistent” will give out the following errors:

root@chinas:/opt/open-nti# make start-persistent
Use docker compose file: docker-compose/opennti_persistent.yml
IMAGE_TAG=latest docker-compose -f docker-compose/opennti_persistent.yml up -d
ERROR: build path /opt/open-nti/docker-compose/plugins/input-snmp either does not exist, is not accessible, or is not a valid URL.
Makefile:79: recipe for target 'start-persistent' failed
make: *** [start-persistent] Error 1
root@chinas:

I have to copy the plugin directory to open-nti/docker-compose/ to make it work.

**Comment by 3fr61n** [comment]
Regarding the input-snmp issue I committed #fe154b0

**Comment by zhanghaofeng** [comment]
Great. But I never made this input-snmp work ☹
Maybe we can do a live troubleshooting together? I can demo the problems in this module.

**Comment by 3fr61n** [comment]
Did you have the chance to take a look for 
http://open-nti.readthedocs.io/en/latest/snmpcollectionagent.html

**Comment by zhanghaofeng** [comment]
Yes. Several times.
I see 2 issues here:


1.      “ADD templates /data/templates/” in input-snmp/Dockerfile doesn’t take effect. No matter how I change the template file in input-snmp/template/telegraf.tmp, the change won’t reflect to the opennti-input-snmp container

2.      I find a way to workaround above problem. But the SNMP polling result cannot go to influxdb database.
