### ISSUE TITLE
cosmetic: main page link to 'open an issue' returns Error 404

### ISSUE THREAD

**Issue by lorenzomurillo** [Juniper/open-nti#16]
On the main page:
"For any issues please open an issue on Github For comments, suggestions or questions please use our google group"
The link "https://github.com/Juniper/open-nti/blob/master/issues" gives a 404 error.

**Comment by 3fr61n** [comment]
Not sure if this is a problem of openNTI or related to github.  let me know if it happens again.

**Comment by 3fr61n** [comment]
I'll close the issue (because it seem not related to openNTI), if this happen again, please reopen it.

**Comment by dgarros** [comment]
I'll Take it
