### ISSUE TITLE
Interface Statistics showing incorrect data

### ISSUE THREAD

**Issue by pr-acassera** [Juniper/open-nti#172]
Upgraded two QFX switches this weekend from 14.1X53-D30 and D35 to 14.1X53-D42.3.  Now interface statistics are showing incorrectly.  I believe, the actual numbers being incremented by 8.  Normally 490 to 500Mbps is showing as around 3.9 to 4.0 Gbps.  Is this graph int-bps.yaml file?  Can I Alter this?

**Comment by 3fr61n** [comment]
It's weird because from openNTI perspective there is no change related on parsing or process JTI packets.

You can alter all charts and dashboard on grafana, but remember that predefined dashboard are readonly, so make your changes on the original dashboard then use 'save as' and create your own

**Comment by pr-acassera** [comment]
Okay updated dashboard and fixed the problem.  The query was multiplying by 8.
