### ISSUE TITLE
Using input-snmp plugin

### ISSUE THREAD

**Issue by vascojcm** [Juniper/open-nti#179]
Hi, 
I'm trying to use the input-snmp plugin to collect some OID metrics. 
I really cannot understand what is happening because the collector is always trying to snmpwalk through the default hosts that are shown as example on the telegraf.tmpl file (172.30.137.90 && 172.30.137.93).

I've already commented these hosts from the config file, already rebuilt the input-snmp plugin and even already restarted all the docker container. 

root@<my_host>:/opt/open-nti# grep -r "172.30.137" *
docs/snmpcollectionagent.rst:#    agents = [ "172.30.137.90:161","172.30.137.93:161" ]  # this is an example for a single snmp get 
plugins/input-snmp/templates/telegraf.tmpl:#  agents = [ "172.30.137.90:161","172.30.137.93:161" ]

However, I'm not able to pull any of my new configured hosts on the agents field.
This is not a problem regarding snmp configuration since I have all the communities and whitelists correctly configured. 
Also, when I do a tcpdump in my open-nti host I'm observing that it is still trying to snmpwalk through the example hosts (172.16.30.X) and none of my new configured hosts !!!

Am I missing something here ?
I've strictly followed the steps described on the documentation and the "walking" through my real hosts is simply not happening. 

Best Regards

**Comment by 3fr61n** [comment]
Hi

Coulds you please access the shell of the snmp container and do 

cat /opt/telegraf/config/telegraf.conf

So you can confirm which host are being configured?

Regards

**Comment by vascojcm** [comment]
Hi Efrain, 

Actually I don't have that folder.

the only telegraf.conf that I have is on the folder /opt/open-nti/docker/telegraf/telegraf.conf (where I've installed open-nti)

I've cloned the project as it is in git. 
Was supposed to have the telegraf.conf file in that folder ?

Here is the output of that file:
########################
root@<my_host>:/opt/open-nti# grep -v "#" /opt/open-nti/docker/telegraf/telegraf.conf 
[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  debug = true
  quiet = false
  hostname = ""
  omit_hostname = false

[[outputs.influxdb]]
  precision = "s"
  retention_policy = "default"
  write_consistency = "any"
  timeout = "5s"

[[inputs.statsd]]
  service_address = ":8125"
  delete_gauges = true
  delete_counters = false
  delete_sets = false
  delete_timings = true
  percentiles = [90]
  convert_names = true
  allowed_pending_messages = 10000
  percentile_limit = 1000
  udp_packet_size = 1500


Also here is the output of telegraf.tmpl file 
########################
root@<my_host>:/opt/open-nti# grep -v "#" plugins/input-snmp/templates/telegraf.tmpl 
[tags]
  dc = "my_tag"

[agent]
  interval = "2m"
  round_interval = true
  flush_interval = "30s"
  flush_jitter = "0s"
  debug = true
  hostname = "my_host"

[[outputs.influxdb]]
  urls = ["http://opennti:8086"]
  database = "snmp"
  precision = "s"
  retention_policy = ""
  timeout = "5s"

[[inputs.snmp]]
  agents = ["host1:161","host2:161"]
  version = 2
  community = "my_community"

  name = "system"
  [[inputs.snmp.field]]
    name = "hostname"
    oid = ".1.3.6.1.2.1.1.5.0"
    is_tag = true
  [[inputs.snmp.field]]
    name = "uptime"
    oid = ".1.3.6.1.2.1.1.3.0"


Thank you very much for the help

**Comment by 3fr61n** [comment]
You are inside the main container and not into the snmp container,  in order to access the plugin container you need to execute

docker exec -i -t "container-Id" /bin/bash

Regards

**Comment by vascojcm** [comment]
Thank you for your quick answer!

However, no luck !

# docker ps | grep snmp
192b261e1602        opennti_input-snmp                     "/source/start-inp..."   3 days ago          Up 3 days           0.0.0.0:162->162/udp                                                                                                 opennti_input_snmp

#docker exec -i -t 192b261e1602 /bin/bash
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory"

**Comment by 3fr61n** [comment]
Try /bin/ash instead of /bin/bash

(It's alpine linux sorry)

**Comment by vascojcm** [comment]
Efrain, 

Thank you so much, it is working now.
This is not clear on the documentation that's why I was wandering what could be happening.

I will explore now the snmp data gathering since I'm finding some issues creating some junos-parsers (issue #173)  =)
 
Best Regards
