### ISSUE TITLE
installation warning: no previously-included files matching '*.pyc' found anywhere in distribution

### ISSUE THREAD

**Issue by lorenzomurillo** [Juniper/open-nti#18]
Hi team, 
when issuing "sudo ./docker.build.sh", a warning appears.
warning: no previously-included files matching '*.pyc' found anywhere in distribution
zip_safe flag not set; analyzing archive contents...
ply.lex: module references __file__
ply.lex: module MAY be using inspect.getsourcefile
ply.yacc: module references __file__
ply.yacc: module MAY be using inspect.getsourcefile
ply.yacc: module MAY be using inspect.stack
ply.ygen: module references __file__

Installing on Ubuntu 14.04 Desktop vm
ubuntu@ubuntu-virtual-machine:/usr/share/gnome-connection-manager$ uname -a
Linux ubuntu-virtual-machine 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@ubuntu-virtual-machine:/usr/share/gnome-connection-manager$ docker -v
Docker version 1.10.2, build c3959b1

Searching for ply
Reading https://pypi.python.org/simple/ply/
Best match: ply 3.8
Downloading https://pypi.python.org/packages/source/p/ply/ply-3.8.tar.gz#md5=94726411496c52c87c2b9429b12d5c50
Processing ply-3.8.tar.gz
Writing /tmp/easy_install-czFJXK/ply-3.8/setup.cfg
Running ply-3.8/setup.py -q bdist_egg --dist-dir /tmp/easy_install-czFJXK/ply-3.8/egg-dist-tmp-n4TOD8
warning: no previously-included files matching '*.pyc' found anywhere in distribution
zip_safe flag not set; analyzing archive contents...
ply.lex: module references __file__
ply.lex: module MAY be using inspect.getsourcefile
ply.yacc: module references __file__
ply.yacc: module MAY be using inspect.getsourcefile
ply.yacc: module MAY be using inspect.stack
ply.ygen: module references __file__
Adding ply 3.8 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/ply-3.8-py2.7.egg

**Comment by 3fr61n** [comment]
I check and those are warning are not relevant for the OpenNTI operation.

Thanks for noticing
