### ISSUE TITLE
Query for Data collection show interface media

### ISSUE THREAD

**Issue by pr-acassera** [Juniper/open-nti#181]
What is the correct Query in grafana for the show interface media data.  I want to show bit rate.  I am getting negative results in what I am trying to do.  Maybe I do not understand what the influx function mean is doing.

select mean(delta) from /($host_regex).interface.*.output-bps/ where $timeFilter group by time($interval)

**Comment by 3fr61n** [comment]
Hi,  

Could you please try and change mean(delta) with mean(value)?

PS:  output-bps values are already the numbers that you want to plot, not the 'delta' between each sample.

Regards

**Comment by pr-acassera** [comment]
Thank you.
