### ISSUE TITLE
Expose extra measurements for lw4o6 (dropped, fragments)

### ISSUE THREAD

**Issue by kzorba** [Juniper/open-nti#183]
A few extra measurements are needed for a good monitoring of a lwAFTR infrastructure.
After a couple of months of pilot operation some extra metrics were needed for us that had to do with dropped packets and fragment handling. Those counters are exposed in the underlying Snabb and we get them via VMX JunOS.
A pull request will follow for this issue.

**Comment by 3fr61n** [comment]
Already merged

Thanks
