### ISSUE TITLE
Wrong interface bandwidth after JunOS update

### ISSUE THREAD

**Issue by mziegler8888** [Juniper/open-nti#191]
Good Morning,

yesterday I updated one of our QFX5100 from JunOS 14.1X53-D35.3 to 14.1X53-D45.3. After that traffic statistics for all interfaces increased. My first impression was that data has changed bits/s to bytes/s (see attached screenshot). Any ideas  please?

Thank you,

Martin

![screen shot 2017-11-10 at 08 34 24](https://user-images.githubusercontent.com/22808391/32647543-1c0b58f2-c5f2-11e7-94fd-a86929261e81.png)

**Comment by 3fr61n** [comment]
To be honest I think you're right, I think someone else told me that too, the workaround is to multiply or divide by 8 on you grafana charts

**Comment by mziegler8888** [comment]
Not nice :( Unfortunately now I have devices with both JunOS versions. How should I divide by 8 based on the JunOS version within one single query? 

Thank you,

Martin Ziegler

**Comment by 3fr61n** [comment]
Create in the same charts, 2 queries, both queries will have q 'where' clause matching (or not) version to the new junos, and only apply the workaround in the new query

**Comment by mziegler8888** [comment]
Yes, but I cannot find the JunOS version as a metric?!

Thank you,

Martin

**Comment by mziegler8888** [comment]
Just added the show-version parsed to my config ;) Sorry for that and thanks for your help.
