### ISSUE TITLE
Open-nti is not decoding new sensors

### ISSUE THREAD

**Issue by seaswar2505** [Juniper/open-nti#195]
Hi,

I installed latest version of open-nti on my server and installation was successful.
I have configured few sensors on my setup. I can see packets in the InfluxDB from few sensors only (Interfaces and CPU memory). The more recent sensors like PFE Statistics, Segment routing stats are not getting decoded on the server. 
1) Do we have a list of supported sensors for open-nti?
2) If not all are supported, is the tool modular to add new sensors?

Working sensors:
/junos/system/linecard/interface/
/junos/system/linecard/interface/logical/usage/
/junos/system/linecard/cpu/memory/

Below sensors packets are not decoded with latest open-nti version:
/junos/system/linecard/npu/memory/
/junos/system/linecard/packet/usage/
/junos/services/segment-routing/interface/egress/usage/

Thanks,
Swetha.

**Comment by mpergament** [comment]
Hi,

it is not implemented yet:
https://github.com/JNPRAutomate/fluent-plugin-juniper-telemetry/blob/master/lib/fluent/plugin/parser_juniper_jti.rb

Michael

**Comment by mpergament** [comment]
Seems tech mocha extended it already: https://github.com/tech-mocha/fluent-plugin-juniper-telemetry/tree/master/junos-telemetry

Can you please try it?

**Comment by seaswar2505** [comment]
Thanks Michael.

Do I need to update only the Fluentd plugin or upgrade Open-nti with a new version? Could you point me to the steps to do this?

Regards,
Swetha.

**Comment by mpergament** [comment]
Sorry it does not have code for sensors you mentioned above.

**Comment by mpergament** [comment]
One Juniper developer has already generic code (internal repository) to support any sensor in a very flexible way. I hope he can commit his work very soon.

**Comment by henriklb** [comment]
That would be great.

**Comment by psagrera** [comment]
OpenNTI already supports sensors mentioned on this issue.
