### ISSUE TITLE
Persistent data lost with Dashboards

### ISSUE THREAD

**Issue by jgeromero** [Juniper/open-nti#198]
Hi all,

I remember starting open-nti with 'make start-persistent' and I recently stopped and restarted again but now my db is empty and dashboards gone. Can someone please clarify what the right process is to keep things persistent, including grafana dashboards. From other tickets here, it seems that I needed to do a 'docker commit' which I did not do. 

I spent hours working on different dashboards :(  from the docs it looks like start-persistent makes a copy of dashboards outside of the container? 

Thank you!

**Comment by vascojcm** [comment]
Hi, 

I ran into the same problem as you before. 

In the grafana dashboard go to Settings (little wheel icon) > View JSON

Copy all the JSON code into clipboard and save it on your open-nti dashboard folder (something like /<your_specific_path>/open-nti/dashboards/ )

**Comment by jgeromero** [comment]
Thanks @vascojcm that's what I've been doing so far. Looks like database files are also stored in the data directory.
