### ISSUE TITLE
Error after installing - D! Retrying 10.255.32.154 with timeout 1s

### ISSUE THREAD

**Issue by mnanduri** [Juniper/open-nti#205]
I rebuilt the instance this afternoon, once its done seeing this error for -OC. The device 10.255.32.154 is reachable from the container and can telnet to device using port 50051.

Attached is also telegraf.tmpl file.

docker logs opennti_input_oc
2018-02-09T21:34:15Z D! Output [influxdb] buffer fullness: 0 / 10000 metrics.
2018-02-09T21:34:15Z D! Retrying 10.255.32.154 with timeout 1s
2018-02-09T21:34:15Z D! Retrying 10.255.32.154 with timeout 1s
2018-02-09T21:34:15Z D! Retrying 10.255.32.154 with timeout 1s
2018-02-09T21:34:16Z D! Retrying 10.255.32.154 with timeout 1s
2018-02-09T21:34:16Z D! Retrying 10.255.32.154 with timeout 1s
2018-02-09T21:34:16Z D! Retrying 10.255.32.154 with timeout 1s
2018-02-09T21:34:17Z D! Retrying 10.255.32.154 with timeout 1s
2018-02-09T21:34:17Z D! Retrying 10.255.32.154 with timeout 1s
2018-02-09T21:34:17Z D! Retrying 10.255.32.154 with timeout 1s
2018-02-09T21:34:18Z D! Retrying 10.255.32.154 with timeout 1s
2018-02-09T21:34:18Z D! Retrying 10.255.32.154 with timeout 1s
2018-02-09T21:34:18Z D! Retrying 10.255.32.154 with timeout 1s
2018-02-09T21:34:19Z D! Retrying 10.255.32.154 with timeout 1s
2018-02-09T21:34:19Z D! Retrying 10.255.32.154 with timeout 1s
2018-02-09T21:34:19Z D! Retrying 10.255.32.154 with timeout 1s

root@lvstelemetry-1609572:/mnt/open-nti# docker exec -i -t 97c4367e1e26 /bin/bash
root@97c4367e1e26:/source# ping 10.255.32.154
PING 10.255.32.154 (10.255.32.154): 56 data bytes
64 bytes from 10.255.32.154: icmp_seq=0 ttl=52 time=1.884 ms
64 bytes from 10.255.32.154: icmp_seq=1 ttl=52 time=0.847 ms
^C--- 10.255.32.154 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.847/1.365/1.884/0.519 ms

root@97c4367e1e26:/source# telnet  10.255.32.154 50051
Trying 10.255.32.154...
Connected to 10.255.32.154.
Escape character is '^]'.
▒^CConnection closed by foreign host.
root@97c4367e1e26:/source#

[telegraf.tmpl.txt](https://github.com/Juniper/open-nti/files/1712715/telegraf.tmpl.txt)

**Comment by 3fr61n** [comment]
Hi

Question, it's the first time configuring OC?

Does the device has all OC packages properly configured?

Regards

**Comment by mnanduri** [comment]
It worked before. I reinstalled opennti again to make sure also.

I think so, is there a way to ensure it has all the packages properly.

root@1609572:/home/root# docker ps -a
CONTAINER ID        IMAGE
COMMAND                  CREATED             STATUS
PORTS
NAMES
97c4367e1e26        opennti_input-oc
"/source/start-inp..."   3 days ago          Up 3 days
0.0.0.0:50051->50051/udp
opennti_input_oc
bb8a3f529acd        juniper/open-nti-input-syslog:latest   "/bin/sh -c
/home/..."   3 days ago          Up 3 days           5140/tcp, 24220/tcp,
24224/tcp, 0.0.0.0:6000->6000/udp
opennti_input_syslog
940adec55da1        juniper/open-nti-input-jti:latest
"/bin/entrypoint.s..."   3 days ago          Up 3 days           5140/tcp,
24224/tcp, 0.0.0.0:50000->50000/udp, 24284/tcp,
0.0.0.0:50020->50020/udp
opennti_input_jti
6e6d475da96e        opennti_input-snmp
"/source/start-inp..."   3 days ago          Up 3 days
0.0.0.0:162->162/udp
opennti_input_snmp
76f6b4086165        opennti_input-internal
"/source/start-inp..."   3 days ago          Up 3
days
opennti_input_internal
50b33be739ce        juniper/open-nti:latest
"/sbin/my_init"          3 days ago          Up 3 days
0.0.0.0:80->80/tcp,
0.0.0.0:3000->3000/tcp, 0.0.0.0:8083->8083/tcp, 0.0.0.0:8086->8086/tcp,
0.0.0.0:8125->8125/udp   opennti_con

**Comment by 3fr61n** [comment]
Hi

Do you see any related message on the device?  Could you check in 'show log na-grpcd' 

Regards

**Comment by mnanduri** [comment]
Nope... below is the output 

lab@m1-bcr1> show log na-grpcd | last 100
Feb 02 06:06:06  #29989# getsockopt: Socket receive buffer size is 8388608 for client-1
Feb 02 06:06:06  #29990# Subscription client-1 MQTT subscribe path: /1000
Feb 02 06:10:19  #29991# Subscription client-1 MQTT bus disconnected.
Feb 02 06:10:20  #29992# Subscribing for  client-1
Feb 02 06:10:20  #29993# setsockopt: Setting receive buffer size to 8388608 for client-1
Feb 02 06:10:20  #29994# getsockopt: Socket receive buffer size is 8388608 for client-1
Feb 02 06:10:20  #29995# Subscription client-1 MQTT subscribe path: /1000
Feb 02 06:14:04  #29996# Subscription client-1 MQTT bus disconnected.
Feb 02 06:14:05  #29997# Subscribing for  client-1
Feb 02 06:14:05  #29998# setsockopt: Setting receive buffer size to 8388608 for client-1
Feb 02 06:14:05  #29999# getsockopt: Socket receive buffer size is 8388608 for client-1
Feb 02 06:14:05  #30000# Subscription client-1 MQTT subscribe path: /1000
Feb 02 06:19:04  #30001# Subscription client-1 MQTT bus disconnected.
Feb 02 06:19:05  #30002# Subscribing for  client-1
Feb 02 06:19:05  #30003# setsockopt: Setting receive buffer size to 8388608 for client-1
Feb 02 06:19:05  #30004# getsockopt: Socket receive buffer size is 8388608 for client-1
Feb 02 06:19:05  #30005# Subscription client-1 MQTT subscribe path: /1000
Feb 02 06:22:04  #30006# Subscription client-1 MQTT bus disconnected.
Feb 02 06:22:05  #30007# Subscribing for  client-1
Feb 02 06:22:05  #30008# setsockopt: Setting receive buffer size to 8388608 for client-1
Feb 02 06:22:05  #30009# getsockopt: Socket receive buffer size is 8388608 for client-1
Feb 02 06:22:05  #30010# Subscription client-1 MQTT subscribe path: /1000
Feb 02 06:26:19  #30011# Subscription client-1 MQTT bus disconnected.
Feb 02 06:26:20  #30012# Subscribing for  client-1
Feb 02 06:26:20  #30013# setsockopt: Setting receive buffer size to 8388608 for client-1
Feb 02 06:26:20  #30014# getsockopt: Socket receive buffer size is 8388608 for client-1
Feb 02 06:26:20  #30015# Subscription client-1 MQTT subscribe path: /1000
Feb 02 06:32:49  #30016# Subscription client-1 MQTT bus disconnected.
Feb 02 06:32:50  #30017# Subscribing for  client-1
Feb 02 06:32:50  #30018# setsockopt: Setting receive buffer size to 8388608 for client-1
Feb 02 06:32:50  #30019# getsockopt: Socket receive buffer size is 8388608 for client-1
Feb 02 06:32:50  #30020# Subscription client-1 MQTT subscribe path: /1000
Feb 02 06:35:49  #30021# Subscription client-1 MQTT bus disconnected.
Feb 02 06:35:50  #30022# Subscribing for  client-1
Feb 02 06:35:50  #30023# setsockopt: Setting receive buffer size to 8388608 for client-1
Feb 02 06:35:50  #30024# getsockopt: Socket receive buffer size is 8388608 for client-1
Feb 02 06:35:50  #30025# Subscription client-1 MQTT subscribe path: /1000
Feb 02 06:38:49  #30026# Subscription client-1 MQTT bus disconnected.
Feb 02 06:38:50  #30027# Subscribing for  client-1
Feb 02 06:38:50  #30028# setsockopt: Setting receive buffer size to 8388608 for client-1
Feb 02 06:38:50  #30029# getsockopt: Socket receive buffer size is 8388608 for client-1
Feb 02 06:38:50  #30030# Subscription client-1 MQTT subscribe path: /1000
Feb 02 06:40:20  #30031# Subscription client-1 MQTT bus disconnected.
Feb 02 06:40:21  #30032# Subscribing for  client-1
Feb 02 06:40:21  #30033# setsockopt: Setting receive buffer size to 8388608 for client-1
Feb 02 06:40:21  #30034# getsockopt: Socket receive buffer size is 8388608 for client-1
Feb 02 06:40:21  #30035# Subscription client-1 MQTT subscribe path: /1000
Feb 02 06:43:19  #30036# Subscription client-1 MQTT bus disconnected.
Feb 02 06:43:20  #30037# Subscribing for  client-1
Feb 02 06:43:20  #30038# setsockopt: Setting receive buffer size to 8388608 for client-1
Feb 02 06:43:20  #30039# getsockopt: Socket receive buffer size is 8388608 for client-1
Feb 02 06:43:20  #30040# Subscription client-1 MQTT subscribe path: /1000
Feb 02 06:48:49  #30041# Subscription client-1 MQTT bus disconnected.
Feb 02 06:48:50  #30042# Subscribing for  client-1
Feb 02 06:48:50  #30043# setsockopt: Setting receive buffer size to 8388608 for client-1
Feb 02 06:48:50  #30044# getsockopt: Socket receive buffer size is 8388608 for client-1
Feb 02 06:48:50  #30045# Subscription client-1 MQTT subscribe path: /1000
Feb 02 06:52:49  #30046# Subscription client-1 MQTT bus disconnected.
Feb 02 06:52:50  #30047# Subscribing for  client-1
Feb 02 06:52:50  #30048# setsockopt: Setting receive buffer size to 8388608 for client-1
Feb 02 06:52:50  #30049# getsockopt: Socket receive buffer size is 8388608 for client-1
Feb 02 06:52:50  #30050# Subscription client-1 MQTT subscribe path: /1000
Feb 02 06:55:34  #30051# Subscription client-1 MQTT bus disconnected.
Feb 02 06:55:35  #30052# Subscribing for  client-1
Feb 02 06:55:35  #30053# setsockopt: Setting receive buffer size to 8388608 for client-1
Feb 02 06:55:35  #30054# getsockopt: Socket receive buffer size is 8388608 for client-1
Feb 02 06:55:35  #30055# Subscription client-1 MQTT subscribe path: /1000
Feb 02 06:58:34  #30056# Subscription client-1 MQTT bus disconnected.
Feb 02 06:58:35  #30057# Subscribing for  client-1
Feb 02 06:58:35  #30058# setsockopt: Setting receive buffer size to 8388608 for client-1
Feb 02 06:58:35  #30059# getsockopt: Socket receive buffer size is 8388608 for client-1
Feb 02 06:58:35  #30060# Subscription client-1 MQTT subscribe path: /1000
Feb 02 07:06:04  #30061# Subscription client-1 MQTT bus disconnected.
Feb 02 07:06:05  #30062# Subscribing for  client-1
Feb 02 07:06:05  #30063# setsockopt: Setting receive buffer size to 8388608 for client-1
Feb 02 07:06:05  #30064# getsockopt: Socket receive buffer size is 8388608 for client-1
Feb 02 07:06:05  #30065# Subscription client-1 MQTT subscribe path: /1000
Feb 02 07:09:04  #30066# Subscription client-1 MQTT bus disconnected.
Feb 02 07:09:05  #30067# Subscribing for  client-1
Feb 02 07:09:05  #30068# setsockopt: Setting receive buffer size to 8388608 for client-1
Feb 02 07:09:05  #30069# getsockopt: Socket receive buffer size is 8388608 for client-1
Feb 02 07:09:05  #30070# Subscription client-1 MQTT subscribe path: /1000
Feb 02 07:12:04  #30071# Subscription client-1 MQTT bus disconnected.
Feb 02 07:12:05  #30072# Subscribing for  client-1
Feb 02 07:12:05  #30073# setsockopt: Setting receive buffer size to 8388608 for client-1
Feb 02 07:12:05  #30074# getsockopt: Socket receive buffer size is 8388608 for client-1
Feb 02 07:12:05  #30075# Subscription client-1 MQTT subscribe path: /1000
Feb 02 07:12:19  #30076# Channel disconnected or Subscription expired: ID = 1, Expired : 0, Client Disconnects :                                        1
Feb 02 07:12:19  #30077# Subscription client-1 MQTT unsubscribe path: /1000
Feb 02 07:12:19  #30078# Subscription client-1 MQTT bus disconnected.
Feb 02 07:12:19  #30079# Remove Request ID: 1
Feb 02 07:12:19  #30080# MGD command to delete config passed. Request_id: 1000 Path: path: "/mpls/signaling-proto                                       cols/rsvp-te/interface-attributes/interface/bandwidth-reservations/bandwidth-reservation/state/" sample_frequency                                       : 15000
Feb 02 07:12:19  #30081# Deleted Internal Id = 1000
Feb 02 07:12:19  #30082# Removed path: "/mpls/signaling-protocols/rsvp-te/interface-attributes/interface/bandwidt                                       h-reservations/bandwidth-reservation/state/" sample_frequency: 15000
Feb 02 07:12:19  #30083# ConsolidatorSystemHandle destroy successful
Feb 02 07:12:19  #30084# Subscription-stream-end: ID = 1

**Comment by mnanduri** [comment]
Any ideas? 
I removed docker and reinstalled it, getting same error.

**Comment by 3fr61n** [comment]
Any proxy issues?

**Comment by mnanduri** [comment]
No. I am able to ping and telnet on port 50051.

Sent from my Windows 10 phone

**Comment by 3fr61n** [comment]
Could you use a tcpdump in order to verify who is closing the connection and why?

**Comment by mnanduri** [comment]
Many thanks Jimmy. It's resolved now.
I added the device ip address to docker-compose file and its working now.

input-oc:
#  image: $INPUT_OC_IMAGE_NAME:$IMAGE_TAG
  environment:
    - "no_proxy=172.17.0.2,10.255.32.154"
