### ISSUE TITLE
make start-persistent question

### ISSUE THREAD

**Issue by mnanduri** [Juniper/open-nti#209]
Wanted to ask a quick clarification question, when you start the instance with start-persistent, the db will be stored outside the container as I understand but do I need to start everytime with make  start-persistent or can i just do make start the next time when i bounce the container?

**Comment by 3fr61n** [comment]
Each time you start the container you should use make persistent,  so the influxd daemon will continue to use the same storage as it was using before

**Comment by mnanduri** [comment]
Perfect, thanks for the quick confirmation.
