### ISSUE TITLE
localtime with Docker on OS/X

### ISSUE THREAD

**Issue by mwiget** [Juniper/open-nti#212]
It is possible to run open-nti on OS/X in Docker, but requires removing the mount of /etc/localtime for all containers in docker-compose.yml. OS/X has that file symlinked to a timezone file and Docker for OS/X doesn't allow that file to be mounted:

```
Use docker compose file: docker-compose.yml
IMAGE_TAG=latest docker-compose -f docker-compose.yml up -d
Creating opennti_con ... error

ERROR: for opennti_con  Cannot start service opennti: b'Mounts denied: \r\nThe path /etc/localtime\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'

ERROR: for opennti  Cannot start service opennti: b'Mounts denied: \r\nThe path /etc/localtime\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'
ERROR: Encountered errors while bringing up the project.
make: *** [start] Error 1
```

Simply removing all /etc/localtime mounts works. 

What would be the recommended option to make this work cross-platform? Grafana has the option to configure the timezone:

<img width="542" alt="screenshot 2018-04-05 11 06 14" src="https://user-images.githubusercontent.com/3111088/38356914-6e81389e-38c1-11e8-80cc-7cd95a0a99e6.png">

Wouldn't that be sufficient?

**Comment by 3fr61n** [comment]
I think it does!

In my personal setup I have in that way.

thanks for posting your tip
