### ISSUE TITLE
run open-nti solution outside of docker

### ISSUE THREAD

**Issue by mohsin106** [Juniper/open-nti#215]
hi, is there a way to run the open-nti solution outside of docker containers? if so are there instructions anywhere you can point me to that would explain how to do this? i would like to be able to use telegraf and influxdb to collect telemetry data from my juniper ptx, which is already configured to send out sensor data.

thank you!
mohsin

**Comment by 3fr61n** [comment]
Hi mohsin

A colleague has an entry in his blog about what you're looking for

https://techmocha.blog/2017/10/31/serving-up-opennti-deconstructed/

Regards
Efrain

**Comment by mohsin106** [comment]
hi efrain,

thank you for the link to the blog it was very helpful. i'm running in to a slight issue when trying to install the fluent juniper plugin. this is what i get:

[root@test17 fluent]# ruby --version
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]

[root@test17 fluent]# cd /etc/fluent/
[root@t17 fluentset]# gem install fluent-plugin-juniper-telemetry
ERROR:  Could not find a valid gem 'fluent-plugin-juniper-telemetry' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - timed out (https://api.rubygems.org/specs.4.8.gz)

i know i have internet connectivity from my server to the internet.

thanks,
mohsin

**Comment by mohsin106** [comment]
made it one step further...from the output it appeared that maybe the influxdb plugin was missing for some reason so i tried running this command (gem install fluent-plugin-influxdb) which from the output completed successfully. now i'm getting the following error about some parser plugin (parser_juniper_jti.rb) when try to start fluentd:

[root@pspnesvr17 etc]# 2018-04-22 06:36:03 -0400 [info]: fluent/log.rb:322:call: parsing config file is succeeded path="/etc/fluent/fluent.conf"
2018-04-22 06:36:03 -0400 [warn]: fluent/log.rb:342:call: 'type' is deprecated parameter name. use '@type' instead.
2018-04-22 06:36:03 -0400 [trace]: fluent/log.rb:281:call: registered output plugin 'copy'
2018-04-22 06:36:03 -0400 [warn]: fluent/log.rb:342:call: 'type' is deprecated parameter name. use '@type' instead.
2018-04-22 06:36:03 -0400 [debug]: fluent/log.rb:302:call: adding store type="influxdb"
2018-04-22 06:36:03 -0400 [trace]: fluent/log.rb:281:call: registered output plugin 'influxdb'
2018-04-22 06:36:03 -0400 [trace]: fluent/log.rb:281:call: registered buffer plugin 'memory'
2018-04-22 06:36:03 -0400 [trace]: fluent/log.rb:281:call: registered input plugin 'udp'
/usr/local/rvm/gems/ruby-2.2.2/gems/fluent-plugin-juniper-telemetry-0.3.0/lib/fluent/plugin/parser_juniper_jti.rb:12:in `<class:TextParser>': uninitialized constant Fluent::TextParser::Parser (NameError)
        from /usr/local/rvm/gems/ruby-2.2.2/gems/fluent-plugin-juniper-telemetry-0.3.0/lib/fluent/plugin/parser_juniper_jti.rb:11:in `<module:Fluent>'
        from /usr/local/rvm/gems/ruby-2.2.2/gems/fluent-plugin-juniper-telemetry-0.3.0/lib/fluent/plugin/parser_juniper_jti.rb:10:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'



So then I tried installing parser_juniper_jti.rb and received the following error:

[root@pspnesvr17 etc]# gem install fluent-plugin-parser_juniper_jti
ERROR:  Could not find a valid gem 'fluent-plugin-parser_juniper_jti' (>= 0) in any repository
ERROR:  Possible alternatives: fluent-plugin-parse_cookie, fluent-plugin-parser-maybejson, fluent-plugin-parser_cef, fluent-plugin-docker-inspect, fluent-plugin-pagerduty

**Comment by 3fr61n** [comment]
you're welcome
