### ISSUE TITLE
gRPC stream collector dashboard troubleshooting

### ISSUE THREAD

**Issue by crmcguire11** [Juniper/open-nti#217]
I'm having some trouble getting gRPC w/SSL to work on QFX10002. We're running 18.1R1. I haven't been able to find any documentation regarding SSL on the open-nti side. Is it supported in open-nti yet?  I'd prefer to use unencrypted gRPC, but QFX10002 on 18.1R1 doesn't seem to allow this.

root@QFX10002_Top# set system services extension-service request-response grpc ?
Possible completions:
+ apply-groups         Groups from which to inherit configuration data
+ apply-groups-except  Don't inherit configuration data from these groups
  max-connections      Maximum number of connections (1..30)
> ssl                  SSL based API connection settings

**Comment by jimmyjs1607** [comment]
Hi, clear text is a hidden configuration knob in Junos, try adding it manually.

**Comment by crmcguire11** [comment]
Definitely getting data...

grep write influxdb.log
....
[httpd] 172.17.0.5 - juniper [04/May/2018:11:30:50 -0400] "POST /write?consistency=any&db=juniper HTTP/1.1" 204 0 "-" "-" 1fe93332-4fb0-11e8-a27d-000000000000 47632
[httpd] 172.17.0.5 - juniper [04/May/2018:11:30:55 -0400] "POST /write?consistency=any&db=juniper HTTP/1.1" 204 0 "-" "-" 22e427b5-4fb0-11e8-a27e-000000000000 62418

**Comment by crmcguire11** [comment]
Well, I was using older resources to configure this. I have now successfully been able to collect data using the agent. However, I am still having issues collecting streaming data.

**Comment by jimmyjs1607** [comment]
The issue is not clear, you don't see any data being graphed but you see data in the database? Last time I used gRPC there was no preconfigured dashboard/Query so I had to create mine.

**Comment by 3fr61n** [comment]
Hi guys

The really important part is that there is data on the database.

Regarding the dashboards it depend on many other factors.

Not sure which dashboard are you using because there is one for native sensor (jti) (non-grpc), so those queries won’t work on your scenario

My suggestion is to her familiar to build queries/charts for the sensor you’re interested.  I need to check with a colleague if there is any example available for grpc dashboard so you can habe a reference

Regards

**Comment by crmcguire11** [comment]
Hmmm...Your data streaming collector dashboard looks exactly the same as my auto-generated one. I compared them with Notepad++. They are legit exactly the same. I imported yours anyway. Still not working.

[sensors&ephemeral.txt](https://github.com/Juniper/open-nti/files/1980096/sensors.ephemeral.txt)

**Comment by crmcguire11** [comment]
I see....The autogenerated dashboard is looking for the juniper.analyticsd table in InfluxDB, which doesn't exist when streaming grpc.

**Comment by jimmyjs1607** [comment]
Look for a dashboard named RSVP test, I have some queries there. When you're using gRPC the table takes the name of the sensor or you can put a name to it, for example: "Interface /junos/system/linecard/interface/",

Then you can log in to the influx db page and run a query like "select * from Interface" or "select * from ""/junos/services/label-switched-path/""
