### ISSUE TITLE
making behind proxy

### ISSUE THREAD

**Issue by kepatton** [Juniper/open-nti#218]
I've setup the proxy env variables in all the Dockerfile's as well as in /etc/default/docker..

when I try to make start I keep getting this odd error

xx@telemetry:~/open-nti$ sudo -E make start
Use docker compose file: docker-compose.yml
IMAGE_TAG=latest docker-compose -f docker-compose.yml up -d
Pulling opennti (juniper/open-nti:latest)...
ERROR: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Makefile:79: recipe for target 'start' failed
make: *** [start] Error 1

any ideas?
thanks

**Comment by kepatton** [comment]
never mind, found it here.
https://stackoverflow.com/questions/23111631/cannot-download-docker-images-behind-a-proxy

in case some else needs this.

**Comment by 3fr61n** [comment]
Thanks for your comment!
