### ISSUE TITLE
make start fails ERROR: unsatisfiable constraints

### ISSUE THREAD

**Issue by codyrat** [Juniper/open-nti#238]
root@docker-master:~/open-nti# make start
Use docker compose file: docker-compose.yml
IMAGE_TAG=latest docker-compose -f docker-compose.yml up -d
Building input-snmp
Step 1/13 : FROM juniper/pyez:2.1.8
 ---> 09a523c2b46b
Step 2/13 : WORKDIR /source
 ---> Using cache
 ---> f7e9754f1ba4
Step 3/13 : USER root
 ---> Using cache
 ---> 4a66437eaa32
Step 4/13 : RUN apk add --no-cache ca-certificates &&     update-ca-certificates
 ---> Using cache
 ---> fdd956bfd5b8
Step 5/13 : RUN apk add --no-cache wget git
 ---> Running in 11cba06a74e2
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
  git (missing):
    required by: world[git]
ERROR: Service 'input-snmp' failed to build: The command '/bin/sh -c apk add --no-cache wget git' returned a non-zero code: 1
Makefile:80: recipe for target 'start' failed
make: *** [start] Error 1

**Comment by psagrera** [comment]
Hi,

The problem happens every time you try to start openNTI ?  Yesterday  I was able to install from scratch and worked fine. Perhaps it was a temporary issue with a mirror. Could you try again ?

**Comment by psagrera** [comment]
I'm going to close that issue, please re-open it in case you run into the problem again

Thanks 

Pablo
