### ISSUE TITLE
http://kapacitor_con:9092 doesn't resolve

### ISSUE THREAD

**Issue by mdbarrett99** [Juniper/open-nti#247]
Hi,

I have a brand new opennti installation and I've traced JTI coming into the the linux host and then passing through to the container arrangement.  Looking at /var/log/influxdb.log I see these messages which roughly line up with JTI streaming coming from my MX.

[httpd] 172.17.0.3 - juniper [19/Oct/2018:15:06:47 +1100] "POST /write?db=juniper&p=%5BREDACTED%5D&precision=ms&u=juniper HTTP/1.1" 204 0 "-" "Ruby" 663096d6-d354-11e8-82dc-000000000000 6586
ts=2018-10-19T04:06:48.005985Z lvl=info msg="Post http://kapacitor_con:9092/write?consistency=&db=juniper&precision=ns&rp=four_weeks: dial tcp: lookup kapacitor_con on 8.8.8.8:53: no such host" log_id=0BEbm3Il000 service=subscriber
[httpd] 172.17.0.3 - juniper [19/Oct/2018:15:06:49 +1100] "POST /write?db=juniper&p=%5BREDACTED%5D&precision=ms&u=juniper HTTP/1.1" 204 0 "-" "Ruby" 6761e47a-d354-11e8-82dd-000000000000 6632
ts=2018-10-19T04:06:50.007185Z lvl=info msg="Post http://kapacitor_con:9092/write?consistency=&db=_internal&precision=ns&rp=monitor: dial tcp: lookup kapacitor_con on 8.8.8.8:53: no such host" log_id=0BEbm3Il000 service=subscriber
ts=2018-10-19T04:06:50.007229Z lvl=info msg="Post http://kapacitor_con:9092/write?consistency=&db=juniper&precision=ns&rp=four_weeks: dial tcp: lookup kapacitor_con on 8.8.8.8:53: no such host" log_id=0BEbm3Il000 service=subscriber

Given this I'm assuming this is why I don't see anything in my graphs from grafana etc.

Thanks.

Cheers.

M

**Comment by agould123** [comment]
Is kapacitor used in the graphing process ?  

How are you sending your telemetry data from your MX ?  Native or openconfig style ?  

From my MX960, I’m sending native udp port 50000 to opennti’s fluentd then graphing using Chronograf port 8888

Aaron

**Comment by 3fr61n** [comment]
Hi 

Kapacitor is not used so far, is into the default deployment in the case if anyone wnats to use it

Regarss

**Comment by agould123** [comment]
Thanks Efrain, what exactly is kapacitor’s purpose in the OpenNTI suite?  What is it used for?

I’m wondering if kapacitor is for alerting at least.  The reason I say that is because I tried to set up my first alert yesterday in chronograf and it showed me that kapacitor needed to be enabled and I get an error when I try to enable kapacitor in the chronograf GUI

Maybe you can instruct me on what I need to do and what is it used for.

Aaron

**Comment by 3fr61n** [comment]
Exactly this is the idea to setup alarms based on thresholds, etc, you can check the kapacitor web site for more details
