### ISSUE TITLE
No entries in influxdb (Ericsson router 6672 telemetry streaming)

### ISSUE THREAD

**Issue by eaglebow** [Juniper/open-nti#250]

**Comment by 3fr61n** [comment]
Hi

The native udp telemetry plugin for fluentd that is being used by open-nti support the following .proto 
 https://github.com/Juniper/fluent-plugin-udp-native-sensors/tree/master/lib

If you desire yo include your telemetry I suggest to get the your .proto files and compile the source code. (https://github.com/Juniper/fluent-plugin-udp-native-sensors)

Regards

**Comment by eaglebow** [comment]
Hi

Thanks for your quick response. I've found and compiled needed .proto files.
Could you please explain how to integrate them into open-nti? What is my next steps?
