### ISSUE TITLE
ansible details for grafana dashboards generation

### ISSUE THREAD

**Issue by ksator** [Juniper/open-nti#27]
Hello
Could you please share the ansible details (playbooks, jinja2, yaml variiables) you used in this nice demo https://vimeo.com/157599051 to provision new grafana dashbords. 
Many thanks 
Khelil

**Comment by dgarros** [comment]
These haven't been published yet but I'll send you the jnpr internal link, recently we were discussing to use Ansible to generate all defaults dashboards. I think this would be great to have something like that.

Not sure if someone is already working on it 
Thanks
Damien 

cc/ @3fr61n @mpergament
