### ISSUE TITLE
grafana "Data Streaming Collector Dashboard"

### ISSUE THREAD

**Issue by ksator** [Juniper/open-nti#28]
Hello, 
With the "default"  "Data Streaming Collector Dashboard" (the one that came up with this container), can we graph data from 2 qfx? 
I am  unable ot get this working (2 qfx). 
it is ok with one qfx, not ok with 2. 
despite I am receiving (tcpdump) data from 2. 
I have a "no datapoints" in my grafana graphs for the second qfx. 
When I stop the working qfx, I am then able to graph the other one (after some time). 
So I guess this is expected ? Do we need to generate other dashbords (one per device)? 
Many thanks!
Khelil

**Comment by dgarros** [comment]
Hi 

You should be able to graph all devices at the same time
you can select which device to graph using the drop down list on the top left corner of the dashboard.

IF you select `all` or if you type `.*`, you should get all devices, otherwise it's a bug 

Please can you double check and confirm ? 
Thanks

**Comment by nekogtr** [comment]
I also have this exact issue using 2x QFX5100-24Q switches on Junos 14.1X53-D30.3.

The devices appear in the drop down list of the Grafana dashboard but just have "no datapoints". Going through the troubleshooting steps on the Wiki everything appears ok until Step D - Check if data is properly reaching the database.

Show measurements shows "jnpr.analyticsd" correctly, however the DB does not appear to have stored any data for the QFX's when running SELECT * FROM "jnpr.analyticsd" - simply returns Success! (No results to display)

**Comment by MJLIA** [comment]
I am seeing a similar issue with not displaying graphs and I have check the TS steps. 

I am getting data into influx, but it is not graphing anything. 

> SELECT * FROM "jnpr.analyticsd"
name: jnpr.analyticsd
---------------------
time			device	interface	type			value
1456841248000000000	EX-4300	xe-0/2/0	traffic-stats.rxbcpkt	11938
1456841248000000000	EX-4300	xe-0/2/0	traffic-stats.txbyte	1.87201048e+08
1456841248000000000	EX-4300	xe-0/2/0	traffic-stats.txbcpkt	38714
1456841248000000000	EX-4300	xe-0/2/0	traffic-stats.rxcrcerr	0
1456841248000000000	EX-4300	xe-0/2/0	traffic-stats.txmcpkt	15129
1456841248000000000	EX-4300	xe-0/2/0	traffic-stats.txpps	1
1456841248000000000	EX-4300	xe-0/2/0	traffic-stats.rxucpkt	1.077743e+06

I started to test with PPS graph and tried running it on the cli

SELECT mean("value") FROM "jnpr.analyticsd" WHERE ("type" = 'traffic-stats.rxpps' OR "type" = 'traffic-stats.txpps') AND "device" =~ /$host_regex/ AND $timeFilter GROUP BY time($interval), "device", "interface", "type" fill(null)

I receive this error 

ERR: error parsing query: found $, expected identifier, string, number, bool at line 1, char 152

Seems it does not like this part of the statement $timeFilter GROUP BY time($interval), "device", "interface", "type" fill(null)

My install is ubuntu 14.04 and current docker of the project. Any pointers would be helpful on the issue would be great.

**Comment by dgarros** [comment]
Hi
have you check the time on your devices and on the OpenNTI server ?
Time setting are very important 

I data you are showing in your message have a timestamp corresponding to March 1st 2016

To check if you have a time issue, you can try to show "last 1 month" or "last 1 year" in Grafana.

Thanks
Damien

**Comment by MJLIA** [comment]
That was it, thanks for pointing that out.

-J

**Comment by dgarros** [comment]
Great 👍
