### ISSUE TITLE
EX4300 guage appears to be off by a factor of 10.

### ISSUE THREAD

**Issue by mdbarrett99** [Juniper/open-nti#3]
Hi,

In the lab I have a MX104---EX4600---EX4300 in a string and collecting analytics from all 3 devices (they should give me roughly the same values).  I have noticed that the guage for bps for EX4300 out by a factor of 10. The attached file has screen caps of what I'm seeing, which hopefully is attached.

[EX4300bpsguageproblem.docx](https://github.com/Juniper/open-nti/files/140012/EX4300bpsguageproblem.docx)

Respective show version and configuration below.

root@ex4300-01> show version
fpc0:
--------------------------------------------------------------------------
Hostname: ex4300-01
Model: ex4300-24p
Junos: 14.1X53-D30.3
JUNOS EX  Software Suite [14.1X53-D30.3]
JUNOS FIPS mode utilities [14.1X53-D30.3]
JUNOS Crypto Software Suite [14.1X53-D30.3]
JUNOS Online Documentation [14.1X53-D30.3]
JUNOS EX 4300 Software Suite [14.1X53-D30.3]
JUNOS Web Management Platform Package [14.1X53-D30.3]
JUNOS py-base-powerpc [14.1X53-D30.3]

---------------snip

root@ex4300-01> show configuration services
analytics {
    export-profiles {
        exp-prof {
            stream-format json;
            interface {
                statistics {
                    traffic;
                    queue;
                }
            }
        }
    }
    resource-profiles {
        res-prof {
            queue-monitoring;
            traffic-monitoring;
        }
    }
    resource {
        interfaces {
            ge-0/0/0 {
                resource-profile res-prof;
            }
        }
    }
    collector {
        address 2.2.2.2 {
            port 50020 {
                transport udp {
                    export-profile exp-prof;
                }
            }
        }
    }
}

**Comment by mpergament** [comment]
I think it is a query problem for BPS graph. Could you please change it to:
SELECT derivative("value", 1s) FROM "jnpr.analyticsd" WHERE ("type" = 'traffic-stats.rxbps' OR "type" = 'traffic-stats.txbps' )AND "device" =~ /$host_regex$/ AND $timeFilter GROUP BY "device", "interface", "type" fill(null)

And:
SELECT derivative("value", 1s)*8 FROM "jnpr.jvision" WHERE ("type" = 'egress_stats.if_octets' OR "type" = 'ingress_stats.if_octets') AND "device" =~ /$host_regex$/ AND $timeFilter GROUP BY "device", "interface", "type"

**Comment by dgarros** [comment]
Michael 

Mark took a snapshot of his database recently (attached) 
We should be able to reproduce that ourselves now

We used this procedure to do the backup, the link also explains how to do restore
https://docs.influxdata.com/influxdb/v0.10/administration/backup_and_restore/

I've been trying to look at it but hard to find time these days :( if you have the opportunity to look at it, it will be great
Thanks
Damien

[marc_db_20160331.db.save.tar.gz](https://github.com/Juniper/open-nti/files/199908/marc_db_20160331.db.save.tar.gz)

**Comment by mpergament** [comment]
Fixed Grafana zooming issue with JTI.
