### ISSUE TITLE
"show-subscriber-summary/Port" parsers do not have correct RegEx

### ISSUE THREAD

**Issue by mmellin** [Juniper/open-nti#40]
File names affected: 
open-nti > data > junos_parsers > show-subscriber-summary.parser.yaml
open-nti > data > junos_parsers > show-subscriber-summary-port.parser.yaml

Correct syntax should be "subscribers" (plural) and current command file uses "subscriber" (singular).  Please change all references of "subscriber" to "subscribers".

Example:
Incorrect Regex: regex-command: show\s+subscriber\s+summary\s+\|\s+display\s+xml 
Incorrect: variable-name:  $host.bng.subscriber.summary.session-state-active
(Missing last "s" in subscribers)

Correct regex: regex-command: show\s+subscribers\s+summary\s+\|\s+display\s+xml
Correct: variable-name:  $host.bng.subscribers.summary.session-state-active

Happy coding!

**Comment by dgarros** [comment]
Hi @mmellin 
Thanks for reporting this
Is it a cosmetic change or is it currently broken ?
Thanks
Damien

**Comment by mmellin** [comment]
In version of 14.1 on mx, it is broken in that the stats do not collect
because of the XML.

Regards,

Matt

**Comment by 3fr61n** [comment]
Hi @mmellin 

Could you please copy/past the xml output for that command? 

Regards
Efrain

**Comment by mmellin** [comment]
I think it's mainly just missing an S in subscribers.  The current regex
and description say "show system subscriber" and it should be
"subscribers".  Check both the summary and port command.

I can double check the usage when I get back into the office next week.

show subscribers summary port | display xml
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/14.1X50/junos">
    <subscribers-summary-information xmlns="
http://xml.juniper.net/junos/14.1X50/junos-subscribers">
        <counters junos:style="port-summary">
        </counters>
        <counters junos:style="port-summary-total">
            <port-total>0</port-total>
        </counters>
    </subscribers-summary-information>
    <cli>
        <banner></banner>
    </cli>
</rpc-reply>



show subscribers summary | display xml
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/14.1X50/junos">
    <subscribers-summary-information xmlns="
http://xml.juniper.net/junos/14.1X50/junos-subscribers">
        <counters junos:style="state-summary">
            <session-state-total>0</session-state-total>
        </counters>
        <counters junos:style="type-summary">
            <session-type-total>0</session-type-total>
        </counters>
    </subscribers-summary-information>
    <cli>
        <banner></banner>
    </cli>
</rpc-reply>


Regards,

Matt

**Comment by 3fr61n** [comment]
Hi @mmellin 

You are totally right :)

 there is a missing 's' in the parser filename AND inside the file content,  I'll fix it and create the pull request

Regards

**Comment by 3fr61n** [comment]
We'll do the merge with #79
