### ISSUE TITLE
when executing docker.start.persistent.sh it misses open-nti.params file.

### ISSUE THREAD

**Issue by jmizquierdo** [Juniper/open-nti#52]
when executing "sh docker.start.persistent.sh" it misses open-nti.params file at the beginning...

It is needed to add (./) as below to solve the issue:

source ./open-nti.params

**Comment by dgarros** [comment]
Hi 

it might be a platform specific issue because I haven't seen the issue on Mac
Which OS/Shell are you using ? 

Thanks
Damien

**Comment by jmizquierdo** [comment]
It is in a CentOS 7 with bash

José Miguel Izquierdo López
PS Consultant
[X]
m: +34 677 500 289<tel:%2B34%20677%20500%20289>
jizquierdo@juniper.net<mailto:jizquierdo@juniper.net>
www.juniper.net<http://www.juniper.net/>

**Comment by dgarros** [comment]
I made the change on all scripts in #53 
Please let me know if it works better

**Comment by jmizquierdo** [comment]
Now it works fine!

Thanks!

**Comment by jmizquierdo** [comment]
I am reopening the issue, since the following scripts have the same issue:

-rwxrwxr-x. 1 josemi josemi   348 Jun  9 20:53 open-nti-stop-cron.sh
-rwxrwxr-x. 1 josemi josemi   363 Jun  9 20:53 open-nti-start-cron.sh
-rwxrwxr-x. 1 josemi josemi   486 Jun  9 20:53 open-nti-show-cron.sh

**Comment by dgarros** [comment]
Good points, 
Could you fix these and send a pull request ?

**Comment by jmizquierdo** [comment]
Hello,

                I believe I have done it right now, but not sure ☺ (First time I do it!)

Could you confirm, please?

Thanks!

josemi

José Miguel Izquierdo López
PS Consultant
[X]
m: +34 677 500 289<tel:%2B34%20677%20500%20289>
jizquierdo@juniper.net<mailto:jizquierdo@juniper.net>
www.juniper.net<http://www.juniper.net/>

**Comment by dgarros** [comment]
Pull request looks great but for some reason it was closed .. 
I reopened it and merged it
Thanks a lot for your contribution.
Damien
