### ISSUE TITLE
Influx data source not being pre-configured in granfana upon container startup

### ISSUE THREAD

**Issue by mmellin** [Juniper/open-nti#57]
I'm my usage of the latest master branch, when I run either the ./docker.start.sh or the ./docker.start.persistent.sh scripts, once the container comes up there are no data sources pre-configured in grafana.  Is this to be expected?

Getting 502 errors during the CURL calls from the "grafana.init.sh" file:

messages from Nginx_error.log:
2016/06/13 13:15:59 [error] 30#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: _, request: "GET /api/datasources HTTP/1
.1", upstream: "http://127.0.0.1:3000/api/datasources", host: "localhost"
2016/06/13 13:15:59 [error] 30#0: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: _, request: "POST /api/datasources HTTP/
1.1", upstream: "http://127.0.0.1:3000/api/datasources", host: "localhost"

**Comment by dgarros** [comment]
Fixed via #58
