### ISSUE TITLE
The open-nti container doesn't appear persistent between container stops and starts

### ISSUE THREAD

**Issue by mdbarrett99** [Juniper/open-nti#7]
Hi,

Subject says it all.  Very simple demo of changing the profile is attached to demonstrate

[ContainerPersistence.docx](https://github.com/Juniper/open-nti/files/143437/ContainerPersistence.docx)

Essentially everytime you start/stop the container it appears all changes including previously gathered statistics are lost.

Let  me know if you need any other details.

Cheers.

M

**Comment by 3fr61n** [comment]
Hi

This is a inherit behaviour from docker philosophy, in you want to make your changes persistent after stoping the container, you need first to 'commit' your container state (please check last section of this link https://docs.docker.com/engine/quickstart/), then make sure to rename/tag your new images with the proper tag (you can override the original image tags), and then start your container from the latest image you just commited

Regards
Efrain

**Comment by mdbarrett99** [comment]
Hi,

Yep appreciate this and probably haven't asked the question properly.  I was talking with Damian offline and he informs me grafana configuration files are inside the container (as to my example), but the database is outside the container.  I said that would be a very useful addition to move them outside the container (so we can add users to be persistent etc) - whilst typing I noticed issue 8 was just raised.

In addition I guess where this problem really originated from was the influxd database doesn't appear to be persistent.  Looking at the docker.start.sh file in theory /var/lib/influxdb inside the container is mapped to $(pwd)/db outside the container as a volume.  If I ssh to the container, I do see the mapping, but once again nothing is being written to that directory so I'm not sure what is going on there.

Cheers.

M

**Comment by 3fr61n** [comment]
It seems there is another thread about the same issue, #8  , so I'm closing this one
