### ISSUE TITLE
Merge all scripts into a Makefile

### ISSUE THREAD

**Issue by dgarros** [Juniper/open-nti#80]
Hi 

The root directory of the project is becoming crowded with all the `docker.*.sh` and the `open-nti.*.sh` scripts.

I would suggest to centralize all scripts inside a single script/tool that take parameters
I think `make` would do a good job or any other alternative. We could also develop our own shell scripts

Using Make, we could have something like this :

```
./docker.start.sh                >> make start
```

```
./docker.stop.sh                 >> make stop
```

```
./docker.update.sh               >> make update
```

```
./open-nti-show-cron.sh          >> make show-cron
```

```
./open-nti-start-cron.sh         >> make start-cron TAG="tag1"
```

The would be a very quick project, once we agree on something I can do it
Damien

**Comment by 3fr61n** [comment]
Totally agree,  although I'm not familiar with 'make'  I think it make sense to group them all

**Comment by dgarros** [comment]
Done, as part of #95
