### ISSUE TITLE
CG Nat Parser Problems

### ISSUE THREAD

**Issue by vraulsan** [Juniper/open-nti#85]
Hello guys, my name is Andrés Medina, im a network engineer at Auben Networks, im using this tool called Open-NTI, i think is just amazing, but im experiencing some problems with a parser that i created myself.

I was trying to create a parser that allows me to collect some variables of a CG Nat (Carrier Grade Nat) such as port block in use and port block allocation error.
the problem is that the parser is not collecting any variable..

I Already know that, you can create the parser with a type ("Multivalue or Single Value"), both ways are the same, it just differs on the way that it collects the variable. multivalue use loops maybe jumping over the xml, and single value use the entire xpath following the XML Strcuture.

I've tested many Parsers, such like, Show ospf statistics, or picking other variables from the templates.. But the CG Nat parser is not working for me, so i would like to you gus help me out with this, i already have like a month ttrying to do this and i still haven't done it yet.

I posted a thread in Juniper Forums, but got no right answer about it, they just told me to post it here and maybe you guys can help me out

Ill just attach the 2 parsers that i made (Single value - MultiValue) and the XML Output of the Juniper device.

Thanks in advance.

[multi-value-cgnat.txt](https://github.com/Juniper/open-nti/files/529477/multi-value-cgnat.txt)
[single-value-cgnat.txt](https://github.com/Juniper/open-nti/files/529478/single-value-cgnat.txt)
[XML OSPF.txt](https://github.com/Juniper/open-nti/files/529476/XML.OSPF.txt)

also, some support guys in the juniper forum wrote this: 

> parser:
>     regex-command: show\s+services\s+nat\s+pool\s+detail\s+|\s+display\s+xml
>     matches:
>     -
>         type: multi-value
>         method: xpath
>         xpath: //sfw-per-service-set-nat-pool[starts-with(interface-name, 'sp-')]
>         loop: 
>             key: ./interface-name
>             sub-matches:
>             -
>                 xpath: ./service-nat-pool/port-blocks-in-use
>                 variable-name: $host.service-nat-pool.$key.port-blocks-in-use

```
        -
            xpath: ./service-nat-pool/port-block-allocation-errors
            variable-name: $host.service-nat-pool.$key.port-block-allocation-errors
```

and didn't work anyways.

**Comment by 3fr61n** [comment]
Hi Andres

Doing troubleshooting with you we committed this parser 

[Add nat pool parser](https://github.com/Juniper/open-nti/commit/7686167ec177390643ab64f6c384e213d676021b)

And we noticed that in your setup 2 parsers has the same regex-command and open-nti only import import one, after fix it, everything start to work 

Thanks Andres
Regards
