### ISSUE TITLE
show-interfaces-media parser not working.

### ISSUE THREAD

**Issue by vsr2158** [Juniper/open-nti#89]
**I think the show interfaces media parser is not working. I have tried this on two different systems to verify.**

**This is how the commands.yaml looks:**
nti_commands:
   commands: |
      show route summary | display xml
      show interfaces media | display xml
      show pfe statistics traffic | display xml
      show snmp statistics | display xml
   tags: ex mxcontrail

**I have enabled traceoptions for netconf on the device to check incomning rpc.**
Oct 26 15:44:09 [34087] Incoming: <?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:a6
283cd2-1913-4aa5-899b-e0d67a4952bc"><command>show interfaces media </command>/nc:rpc]]>]]>

In influxDB, SHOW MEASUREMENTS does not list any data for interfaces, its listing other things.
I have tried creating a custom parser for interfaces but did not manage yet, a second pair of eyes may help.

Thanks!
- Vijay Shekhar
- vsr@juniper.net

**Comment by vsr2158** [comment]
Okay. I came across this "full xpath expressions do not seem to be supported #39" and understand the issue.. Let me try the workaround to use rfc-compliant netconf.

**Comment by m4ccbr** [comment]
Did the workaround work? could you share it with me :) ?

**Comment by rpetracic** [comment]
Did someone find a solution for this? Still not working correctly.

**Comment by 3fr61n** [comment]
Hi @rpetracic 

The problem is the xpath expression when there are namespaces, could you please try this parser?


```
juniper@naraku:~/scripts/upgrade-grafana/open-nti$ cat data/junos_parsers/show-interfaces-media.parser.yaml 
parser:
    regex-command: show\s+interfaces\s+media\s+\|\s+display\s+xml
    matches:
    -
        type: multi-value
        method: xpath
        xpath: //*[local-name() = 'physical-interface']
        loop:
            key: ./*[local-name() = 'name']
            sub-matches:
            -
                xpath: ./*[local-name() = 'traffic-statistics']/*[local-name() = 'input-bps']
                variable-name:  $host.interface.$key.input-bps



juniper@naraku:~/scripts/upgrade-grafana/open-nti$ make cli
docker exec -i -t opennti_con /bin/bash
root@59e1645fc9a0:/# python /opt/open-nti/open-nti.py -c -s --tag test
Collector Thread-1 scheduled with following hosts: ['172.30.137.140']
Connecting to host: 172.30.137.140
[172.30.137.140]: Executing command: show version | display xml
[172.30.137.140]: Host will now be referenced as : PE1-tf-m320-1-re1
[PE1-tf-m320-1-re1]: Executing command: show interfaces media | display xml
[PE1-tf-m320-1-re1]: Parser found and processed, going to next comand.
[PE1-tf-m320-1-re1]: timestamp_tracking - CLI collection 5
Inserting into database the following datapoints:
[{'fields': {'delta_str': 'N/A', 'value_str': 'm320'},
  'measurement': 'base-info',
  'tags': {'device': 'PE1-tf-m320-1-re1',
           'kpi': 'base-info',
           'product-model': 'm320',
           'version': '13.3R9-S2.1'}},
 {'fields': {'delta': 0, 'value': 0},
  'measurement': 'PE1-tf-m320-1-re1.interface.gr-0/0/0.input-bps',
  'tags': {'device': 'PE1-tf-m320-1-re1',
           'key': 'gr-0/0/0',
           'kpi': 'PE1-tf-m320-1-re1.interface.gr-0/0/0.input-bps',
           'product-model': 'm320',
           'version': '13.3R9-S2.1'}},
 {'fields': {'delta': 0, 'value': 0},
  'measurement': 'PE1-tf-m320-1-re1.interface.ip-0/0/0.input-bps',
  'tags': {'device': 'PE1-tf-m320-1-re1',
           'key': 'ip-0/0/0',
           'kpi': 'PE1-tf-m320-1-re1.interface.ip-0/0/0.input-bps',
           'product-model': 'm320',
           'version': '13.3R9-S2.1'}},
 {'fields': {'delta': 0, 'value': 0},
.....
```

Regards
Efrain

**Comment by rpetracic** [comment]
Thanks Efrain, this is working now. I wonder if there is an easy way to get graphs for all interfaces from one device in Grafana or they have  to be added one by one.

**Comment by 3fr61n** [comment]
If you don't mind I open a new issue to talk about it
