### ISSUE TITLE
OpenNTI - Deployment fine tuning - Data Streaming Collector failing

### ISSUE THREAD

**Issue by jsanz01** [Juniper/open-nti#97]
Hi all,
we are finalizing the OpenNTI deployment & configuration in our project.
OpenNTI - Data Collection part is working properly
However, OpenNTI - Data Streaming Collector is working only partially. I have attached how it looks like by now in Grafana. Only some of the Graphs are showing results.
We have several QFX5100 switches in a Virtual Chassis configuration. We are using Junos: 14.1X53-D35.3
I have also attached a file with our current Analytics configuration.
Could you please let us know what's incorrect in this configuration?
In addition to that, the Graph titled: Interface Queue Stats is warning an error: "InfluxDB Error Response: error parsing query: derivative aggregate requires a GROUP BY interval"

Thank in advance, Jose

[Juniper_Analytics_Config.txt](https://github.com/Juniper/open-nti/files/594245/Juniper_Analytics_Config.txt)
 
[Grafana - Data Steaming Collector Dashboard.pdf](https://github.com/Juniper/open-nti/files/594217/Grafana.-.Data.Steaming.Collector.Dashboard.pdf)

**Comment by dgarros** [comment]
Hi Jose

Glad to see that you are using OpenNTI

The issue with the queue graph is a known issue, I fixed it 2 weeks ago [check the commit here](
https://github.com/Juniper/open-nti/commit/4cc8d7b564ea88cabb5eb8fdf670cc71795b53f8)

Just curious, have you created your dashboard from scratch or are you using the generator that is part of the project ?  
The [documentation of the generator is still slim](http://open-nti.readthedocs.io/en/latest/dashboard.html) but I think it's a very useful tool, let me know if you are interested and if you need help to get started

**Comment by jsanz01** [comment]
Thanks Damien for your input.
we will update the containers.
We are not creating the dashboards.
So, do you think that we should re-generate also the dashboards and not only to update the containers?
If the answer is yes, I can imagine that dashboards generator is the way of doing it. Right?

Best regards, Jose

**Comment by dgarros** [comment]
@jsanz01 

You are correct

If you have not customized the dashboard, you're good   
If you are planning to do so, I would recommend to check the [dashboard generator](http://open-nti.readthedocs.io/en/latest/dashboard.html)

Closing this issue for now, please open a new one  if you have more questions
Thanks
Damien
